// apps/web/src/lib/mock-data.ts

import type { GuardianRelationship, Payment, User } from "@/types";
import type { Document } from "@/types";
// Utilisateurs mockés
export const mockUsers: User[] = [
  {
    id: 1,
    email: 'thomas.parent@example.com',
    passwordHash: 'hash',
    role: 'parent',
    firstName: 'Thomas',
    lastName: 'Parent',
    birthDate: '1980-05-10',
    gender: 'M',
    phone: '+22501020304',
    address: 'Abidjan, Cocody',
    school: null,
    class: null,
    emergencyContactName: null,
    emergencyContactPhone: null,
    registrationStatus: 'actif',
    registrationStep: 'complet',
    notificationPreferences: { email: true, sms: false, push: true },
    attestationData: null,
    createdAt: (new Date() as unknown) as string,
    updatedAt: (new Date() as unknown) as string,
  },
  {
    id: 2,
    email: 'lea.joueuse@example.com',
    passwordHash: 'hash',
    role: 'player',
    firstName: 'Léa',
    lastName: 'Joueuse',
    birthDate: '2010-03-15',
    gender: 'F',
    phone: '+22505060708',
    address: 'Abidjan, Plateau',
    school: 'Lycée Classique',
    class: '4ème',
    emergencyContactName: 'Marie Joueuse',
    emergencyContactPhone: '+22509090909',
    registrationStatus: 'actif',
    registrationStep: 'complet',
    notificationPreferences: { email: true, sms: true, push: true },
    attestationData: {
      signatoryType: 'guardian',
      selectedGuardianIndex: 0,
      signatoryFullName: 'Marie Joueuse',
      acceptedTerms: true,
      signatureUrl: 'https://drive.google.com/...',
    },
    createdAt: (new Date() as unknown) as string,
    updatedAt: (new Date() as unknown) as string,
  },
  {
    id: 3,
    email: 'admin@club.com',
    passwordHash: 'hash',
    role: 'admin',
    firstName: 'Admin',
    lastName: 'Club',
    birthDate: null,
    gender: null,
    phone: '+22511111111',
    address: null,
    school: null,
    class: null,
    emergencyContactName: null,
    emergencyContactPhone: null,
    registrationStatus: 'actif',
    registrationStep: 'complet',
    notificationPreferences: { email: true, sms: false, push: true },
    attestationData: null,
    createdAt: (new Date() as unknown) as string,
    updatedAt: (new Date() as unknown) as string,
  },
  {
    id: 4,
    email: 'super@admin.com',
    passwordHash: 'hash',
    role: 'super_admin',
    firstName: 'Super',
    lastName: 'Admin',
    birthDate: null,
    gender: null,
    phone: '+22522222222',
    address: null,
    school: null,
    class: null,
    emergencyContactName: null,
    emergencyContactPhone: null,
    registrationStatus: 'actif',
    registrationStep: 'complet',
    notificationPreferences: { email: true, sms: false, push: true },
    attestationData: null,
    createdAt: (new Date() as unknown) as string,
    updatedAt: (new Date() as unknown) as string,
  },
];

// Documents mockés
export const mockDocuments: Document[] = [
  {
    id: 1,
    userId: 2,
    type: 'Certificat Medical',
    fileId: 'drive_123',
    publicUrl: 'https://drive.google.com/...',
    isObligatory: true,
    validatedAt: (new Date() as unknown) as string,
    uploadedAt: (new Date() as unknown) as string,
  },
  {
    id: 2,
    userId: 2,
    type: 'Photo d\'identite',
    fileId: 'drive_456',
    publicUrl: 'https://drive.google.com/...',
    isObligatory: true,
    validatedAt: null,
    uploadedAt:  (new Date() as unknown) as string,
  },
];

// Relations parent-enfant mockées
export const mockGuardianRelationships: GuardianRelationship[] = [
  {
    id: 1,
    guardianId: 1,
    playerId: 2,
    relationship: 'Père',
    permissions: { canPay: true, canRegister: true },
    createdAt: (new Date() as unknown) as string,
  },
];

// Paiements mockés
export const mockPayments: Payment[] = [
  {
    id: 1,
    userId: 1,
    amount: 50000,
    method: 'wave',
    transactionReference: 'WAVE123',
    reason: 'Inscription annuelle',
    playerIds: [2],
    status: 'verified',
    declaredAt: (new Date() as unknown) as string,
    verifiedBy: 3,
    verifiedAt: (new Date() as unknown) as string,
  },
  {
    id: 2,
    userId: 1,
    amount: 15000,
    method: 'orange_money',
    transactionReference: 'OM456',
    reason: 'Mensualité mai',
    playerIds: [2],
    status: 'pending',
    declaredAt: (new Date() as unknown) as string,
    verifiedBy: null,
    verifiedAt: null,
  },
];